@baseUrl = http://localhost:3333
@token = {{authenticate_user.response.body.token}}

# Users

# @name register_user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "klevissonws 2",
    "password": "123456"
}

###

# @name authenticate_user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "klevissonws",
    "password": "123456"
}

###

# Videos 

# @name get_all_videos
GET {{baseUrl}}/videos
Content-Type: application/json

###

# @name get_video_by_id
GET {{baseUrl}}/videos/id
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name search_videos_by_title
GET {{baseUrl}}/videos/search?title=
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_videos_by_category
GET {{baseUrl}}/videos/category/categoryId
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name create_new_video
POST {{baseUrl}}/videos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Video teste",
    "description": "descrição",
    "url": "https://www.youtube.com/watch?v=w2doKQXf1vg&t=1164s",
    "categoryId": 1
}

###

# @name update_video
PUT {{baseUrl}}/videos/id
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Teste editando video 2"
}

###

# @name delete_video
DELETE {{baseUrl}}/videos/id
Content-Type: application/json
Authorization: Bearer {{token}}

###

# Categories 

# @name get_all_categories
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_category_by_id
GET {{baseUrl}}/categories/id
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name create_new_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Programação"
}

###

# @name update_category
PATCH {{baseUrl}}/categories/id
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Teste 4"
}

###

# @name delete_category
DELETE {{baseUrl}}/categories/id
Content-Type: application/json
Authorization: Bearer {{token}}